import { Theme, makeStyles, withStyles } from "@material-ui/core/styles";
import { Input } from "@material-ui/core";

export const StyledInput = withStyles((theme) => ({
  root: {
    marginRight: "20px",
    display: "flex",
    height: "44px",
    alignContent: "center",
    padding: "10px",
    border: "1px solid #373F66",
    borderRadius: "100px",
    alignItems: "center",
    color: "white",
    width: "100%",
    "&:before": {
      border: "none",
    },
    "&:hover:not(.Mui-disabled):before": {
      border: "none",
    },
    "&:after": {
      border: "none",
    },
    "& .MuiInputBase-input": {
      paddingLeft: "10px",
      fontWeight: "normal",
      fontSize: "16px",
      color: "#FFFFFF",
      fontFamily: "Lato",
      fontStyle: "Regular",
      lineHeight: "19px",
      align: "Left",
      verticalAlign: "Top",
    },
    "& ::placeholder": {
      opacity: 1 /* Firefox */,
      fontFamily: "Lato",
      fontSize: "16px",
      lineHeight: "19px",
      color: "#70708F",
    },
  },
}))(Input);

export const useStyles = makeStyles((theme: Theme) => ({
  displayNone: {
    display: "none",
  },
  loaderWrapper: {
    position: "fixed",
    zIndex: 99998,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalRoot: {
    padding: "22px 84px 60px 84px",
    position: "fixed",
    width: "650px",
    background: "#282E4E",
    boxShadow: "0px 0px 30px rgba(55, 55, 79, 0.05)",
    borderRadius: "10px",
    textAlign: "center",
    zIndex: 99999,
    maxHeight: "calc(100vh - 32px)",
    overflow: "auto",
    [theme.breakpoints.down(769)]: {
      minWidth: "calc(100% - 32px) !important",
      width: "calc(100% - 32px) !important",
      margin: "0px 50px",
    },
    [theme.breakpoints.down(500)]: {
      padding: "22px 20px 60px 20px",
    },
  },
  closeIcon: {
    position: "absolute",
    top: "20px",
    right: "30px",
  },
  btnRoot: {
    display: "flex",
    width: "100%",
  },
  nextBtn: {
    minWidth: "160px",
    width: "100%",
    marginTop: "20px",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#FFFFFF",
  },
  title: {
    fontStyle: "normal",
    fontFamily: "Montserrat",
    fontWeight: 600,
    fontSize: "25px",
    lineHeight: "50px",
    color: "#FFFFFF",
  },
  description: {
    fontStyle: "normal",
    fontWeight: 400,
    fontFamily: "Lato",
    fontSize: "18px",
    lineHeight: "29px",
    color: "#96A1DB",
  },
  form_field: {
    textAlign: "start",
    marginBottom: "20px",
    [theme.breakpoints.down(769)]: {
      marginBottom: "30px",
    },
  },
  subheader_label: {
    fontFamily: "Lato",
    color: "#96A1DB",
    fontStyle: "Regular",
    fontSize: "12px",
    lineHeight: "14px",
    align: "Left",
    verticalAlign: "Top",
    opacity: "50%",
    marginBottom: "8px",
    marginTop: "24px",
  },
  descriptionTextField: {
    width: "100%",
    marginRight: "20px",
    display: "flex",
    alignContent: "center",
    padding: "10px",
    border: "1px solid #373F66",
    borderRadius: "20px",
    alignItems: "center",
    color: "white",
    paddingLeft: "18px",
    fontFamily: "Lato",
    fontStyle: "Regular",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "19px",
    backgroundColor: "#282e4e",
    minHeight: "100px",
    align: "Left",
    resize: "none",
    verticalAlign: "Top",
    "&:focus-visible": {
      outline: "none",
    },
    "&::placeholder": {
      opacity: 1 /* Firefox */,
      fontFamily: "Lato",
      fontSize: "16px",
      lineHeight: "19px",
      color: "#70708F",
    },
  },
  widthFull: {
    width: "100%",
  },
}));
