import { Theme, makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme: Theme) => ({
  root: {
    display: "flex",
    flexGrow: 2,
    flexFlow: "column nowrap",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
    backgroundColor: " #21263f",
    textAlign: "center",
  },
  content: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    height: "100%",
    maxWidth: "1064px",
    marginLeft: "auto !important",
    marginRight: "auto !important",
    [theme.breakpoints.down(768)]: {
      width: "80%",
    },
  },
  itemContainer: {
    maxWidth: "100% !important",
  },
  title: {
    fontFamily: "Montserrat",
    marginBottom: "1rem",
    position: "relative",
    fontSize: "45px",
    lineHeight: "48px",
    letterSpacing: ".4px",
    minHeight: "1em",
    color: "#fff",
    fontWeight: 600,
    fontStretch: "normal",
    [theme.breakpoints.down(550)]: {
      fontSize: "30px",
    },
  },
  subtitle: {
    color: "#96A1DB",
    marginBottom: "24px",
    marginTop: 0,
    position: "relative",
    fontWeight: 400,
    margin: "calc(2rem - .14286em) 0 1rem",
    fontSize: "18px",
    lineHeight: "28px",
    fontStyle: "normal",
  },
  hero_action: {
    maxWidth: "1064px",
    marginLeft: "auto !important",
    marginRight: "auto !important",
    marginTop: "16px",
    position: "relative",
    fontWeight: 400,
  },
  browsebtn: {
    background: "linear-gradient(90deg, #FF7C4C 20%, #FFB03A 101.82%)",
    color: "#fff",
    width: "190px",
    height: "45px",
    borderRadius: "25px",
    fontSize: "16px",
    lineHeight: "18px",
    minWidth: "128px",
    fontStretch: "normal",
    fontFamily: "Lato",
    textAlign: "center",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    outline: 0,
    border: "none",
    textTransform: "none",
    textDecoration: "none",
    "&:hover": {
      backgroundColor: "#ff3d61",
      cursor: "pointer",
      transform: "translateY(-2px)",
      boxShadow: "0 3px 6px 0 rgb(0 0 0 / 6%)",
    },
  },
  topleftTexture: {
    position: "absolute",
    top: "0px",
    width: "29%",
  },
  toprightTexture: {
    position: "absolute",
    top: "0px",
    right: "0px",
    width: "35%",
  },
  topEllipse1: {
    position: "absolute",
    top: "0px",
    left: "5%",
    width: "16%",
    borderRadius: "100%",
  },
  topEllipse2: {
    position: "absolute",
    top: "25%",
    left: "20%",
    width: "8%",
    borderRadius: "100%",
  },
  topEllipse3: {
    position: "absolute",
    top: "10%",
    right: "10%",
    width: "12%",
    borderRadius: "100%",
  },
}));
