import { Theme, makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme: Theme) => ({
  balanceRoot: {
    display: "flex",
    padding: "19px 20px 19px 30px",
    background: "#282E4E",
    borderRadius: "15px",
    alignItems: "center",
    width: "100%",
    minHeight: "80px",
  },
  balanceDotUcc: {
    minWidth: "6px",
    minHeight: "6px",
    width: "6px",
    height: "6px",
    background: "linear-gradient(#FF7C4C 0%, #FFB03A 100%)",
    borderRadius: "100px",
    marginRight: "9px",
  },
  balanceDescriptionUcc: {
    fontSize: "12px",
    lineHeight: "14px",
    align: "Left",
    opacity: "50%",
    color: "#96A1DB",
    marginRight: "9px",
  },
  balancePercentUcc: {
    fontSize: "20px",
    lineHeight: "30px",
    fontWeight: 600,
    verticalAlign: "Top",
    background: "linear-gradient(#FF7C4C 0%, #FFB03A 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  balanceDotCurrent: {
    minWidth: "6px",
    minHeight: "6px",
    width: "6px",
    height: "6px",
    background: "linear-gradient(#7F64E2 100%, #41A6EF 100%)",
    borderRadius: "100px",
    marginRight: "9px",
  },
  balanceDescriptionCurrent: {
    fontSize: "12px",
    lineHeight: "14px",
    align: "Left",
    opacity: "50%",
    color: "#96A1DB",
    marginRight: "9px",
  },
  balancePercentCurrent: {
    fontSize: "20px",
    lineHeight: "30px",
    fontWeight: 600,
    verticalAlign: "Top",
    background: "linear-gradient(#7F64E2 100%, #41A6EF 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  balanceDotBuyable: {
    minWidth: "6px",
    minHeight: "6px",
    width: "6px",
    height: "6px",
    background: "linear-gradient(#29C98F 100%, #66D8AF 100%)",
    borderRadius: "100px",
    marginRight: "9px",
  },
  balanceDescriptionBuyable: {
    fontSize: "12px",
    lineHeight: "14px",
    align: "Left",
    opacity: "50%",
    color: "#96A1DB",
    marginRight: "9px",
  },
  balancePercentBuyable: {
    fontSize: "20px",
    lineHeight: "30px",
    fontWeight: 600,
    verticalAlign: "Top",
    background: "linear-gradient(#29C98F 100%, #66D8AF 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
}));
